### ISSUE TITLE
Play stops after guessing only first word

### ISSUE THREAD

**Issue by Tam66662** [chetanbhat/quantum-wordle#3]
I've been playing this game for several days now, and only recently got good enough to be able to guess the words. However, whenever I guess the first word correctly, the games immediately ends and tells me what the other word is. Is this the expected gameplay? I would have thought that it would still give me an opportunity to guess the second word.

**Comment by chetanbhat** [comment]
Hi, this behavior is by design as of now. But the feedback is valid that it's not what the player would expect since there is a pair of hidden words.

Like you said, it might be better if we provide an opportunity to guess the second word. I will add support for it in the coming days
