### ISSUE TITLE
qwordle.bhat.ca domain down

### ISSUE THREAD

**Issue by BachoSeven** [chetanbhat/quantum-wordle#7]
The website https://qwordle.bhat.ca is not reachable, the DNS not being resolved. Perhaps you don't want to keep it up anymore, just thought I would share it here.

**Comment by CAnp2015** [comment]
I am SOOO SAD! PLEASE BRING IT BACK, this was my daily routine and wordle just isn't enough without a finishing qwordle challenge!

**Comment by BachoSeven** [comment]
It seems to be back up!
